"""Standalone Connector Pipeline: sales_order_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

# Dependencies
try:
    import pandas as pd
except ImportError:
    pd = None

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except ImportError:
    pa = None
    pq = None

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("sales_order_etl")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "sales_order_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real gcs into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: gcs...")
        if pd is None:
            raise RuntimeError("FATAL: pandas is required for pipeline execution.")
        from google.cloud import storage
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/raw_sales_data.csv"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        client = storage.Client()
        bucket = client.bucket(bucket_name)
        blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]
        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for blob in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(blob.name))
            blob.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with flexible parsing."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        import re
        _FOOTNOTE_RE = re.compile(r"\[[^\]]*\]")
        _NUMERIC_STRIP_RE = re.compile(r"[,$€£¥\s\u00a0]")

        def _normalize_numeric_series(series: pd.Series) -> pd.Series:
            return (
                series.astype(str)
                .str.replace(_FOOTNOTE_RE, "", regex=True)
                .str.replace(_NUMERIC_STRIP_RE, "", regex=True)
                .str.strip()
            )

        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]
        logger.info("Standardized columns: %s", list(df.columns))

        for col in df.columns:
            if pd.api.types.is_string_dtype(df[col]) or pd.api.types.is_object_dtype(df[col]):
                sample = df[col].dropna().head(5)
                if not sample.empty:
                    parsed = pd.to_datetime(sample, errors="coerce")
                    if parsed.notna().sum() >= max(1, len(sample) * 0.6):
                        df[col] = pd.to_datetime(df[col], errors="coerce")
                        logger.info("Auto-parsed column %s as TIMESTAMP", col)

        for col in df.columns:
            if pd.api.types.is_string_dtype(df[col]) or pd.api.types.is_object_dtype(df[col]):
                sample = df[col].dropna().head(10)
                if not sample.empty:
                    cleaned_sample = _normalize_numeric_series(sample)
                    coerced = pd.to_numeric(cleaned_sample, errors="coerce")
                    if coerced.notna().sum() >= max(1, len(sample) * 0.8):
                        _coerced = pd.to_numeric(_normalize_numeric_series(df[col]), errors="coerce")
                        _valid = _coerced.dropna()
                        if not _valid.empty and (_valid % 1 == 0).all():
                            df[col] = _coerced.astype("Int64")
                        else:
                            df[col] = _coerced
                        logger.info("Auto-coerced column %s to numeric", col)

        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip()
            df[col] = df[col].replace({"nan": None, "None": None, "": None})

        # Basic validity filter
        df_valid = df.dropna(how="all")
        quarantined = raw_count - len(df_valid)
        if quarantined > 0:
            logger.warning("Quarantined %d fully-null records", quarantined)

        # Circuit breaker
        if raw_count > 0 and len(df_valid) == 0:
            logger.error("FATAL: 100%% of %d raw records quarantined. Circuit breaker triggered.", raw_count)
            sys.exit(1)

        df_valid = df_valid.copy()
        df_valid["_ingestion_timestamp"] = datetime.utcnow().isoformat()

        df_valid.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid=%d, quarantined=%d", raw_count, len(df_valid), quarantined)
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real bigquery destination."""
        logger.info("Loading staged file %s into bigquery...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Skipping load.")
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "upbeat-repeater-477110-q6"
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "vishesh-test1"

        from google.cloud import bigquery
        from google.api_core.exceptions import NotFound

        try:
            client = bigquery.Client(project=project_id) if project_id else bigquery.Client()
        except Exception as client_init_err:
            raise EnvironmentError(f"FATAL: BigQuery client initialization failed: {client_init_err}") from client_init_err

        table_ref = f"{project_id}.{dataset_id}.{table_id}" if project_id else f"{dataset_id}.{table_id}"

        dataset_ref = client.dataset(dataset_id, project=project_id)
        try:
            client.get_dataset(dataset_ref)
        except NotFound:
            ds = bigquery.Dataset(dataset_ref)
            ds.location = os.getenv("BQ_LOCATION", "us-central1")
            client.create_dataset(ds, exists_ok=True)
            logger.info("Created target dataset: %s", dataset_ref)

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            create_disposition=bigquery.CreateDisposition.CREATE_IF_NEEDED,
            schema_update_options=[
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ],
        )

        schema_file = None
        for cand in [
            os.path.join("schemas", "sales_order_schema.json"),
            os.path.join("schemas", "vishesh-test1_schema.json"),
        ]:
            if os.path.isfile(cand):
                schema_file = cand
                break

        if schema_file:
            raw_schema = client.schema_from_json(schema_file)
            reconciled_schema = []
            for field in raw_schema:
                if field.name not in df.columns:
                    df[field.name] = None
                    reconciled_schema.append(
                        bigquery.SchemaField(
                            name=field.name,
                            field_type=field.field_type,
                            mode="NULLABLE",
                            description=field.description,
                        )
                    )
                else:
                    reconciled_schema.append(field)

            schema_col_names = {sf.name for sf in raw_schema}
            for col in df.columns:
                if col not in schema_col_names:
                    reconciled_schema.append(
                        bigquery.SchemaField(
                            name=col,
                            field_type="STRING",
                            mode="NULLABLE",
                            description=f"Dynamically discovered column '{col}'",
                        )
                    )

            # Type safe coercion
            for field in reconciled_schema:
                col = field.name
                f_type = field.field_type.upper()
                if col in df.columns:
                    if f_type in ("INTEGER", "INT64"):
                        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")
                    elif f_type in ("FLOAT", "FLOAT64", "NUMERIC"):
                        df[col] = pd.to_numeric(df[col], errors="coerce")
                    elif f_type in ("TIMESTAMP", "DATETIME"):
                        df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
                    elif f_type == "STRING":
                        df[col] = df[col].apply(lambda v: str(v) if pd.notna(v) else None)

            job_config.schema = reconciled_schema

        try:
            job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
            job.result()
        except Exception as load_err:
            logger.critical("BigQuery load job failed: %s", load_err, exc_info=True)
            raise load_err

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        try:
            records = self.extract()
            valid_count = self.transform()
            if records > 0 and valid_count == 0:
                logger.error("FATAL: Extracted %d records but 0 valid.", records)
                sys.exit(1)
            self.load()
            logger.info("=== Pipeline Execution Finished Successfully ===")
            return 0
        except Exception as exc:
            logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
            sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline execution FAILED: %s", exc, exc_info=True)
        sys.exit(1)
