"""Standalone Connector Pipeline: daily_sales
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime

import pandas as pd
from google.cloud import storage, bigquery
from google.cloud.exceptions import NotFound

from pipeline.transformer import clean_and_transform_sales

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("daily_sales")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.utcnow().strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "daily_sales", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real GCS into staging format."""
        logger.info("Starting real extraction from source: GCS...")
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/raw_sales_data.csv"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        client = storage.Client()
        bucket = client.bucket(bucket_name)

        blob = bucket.blob(prefix)
        if blob.exists():
            blobs = [blob]
        else:
            blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]

        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for b in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(b.name))
            b.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Transforms and cleans staged records using pipeline transformer."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))
        df_valid = clean_and_transform_sales(df)

        # Overwrite staging file with cleaned data
        df_valid.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid=%d", raw_count, len(df_valid))
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real BigQuery destination."""
        logger.info("Loading staged file %s into BigQuery (analytics.daily_sales)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = (
            os.getenv("GCP_PROJECT_ID")
            or os.getenv("PROJECT_ID")
            or os.getenv("GOOGLE_CLOUD_PROJECT")
            or os.getenv("GCLOUD_PROJECT")
            or "upbeat-repeater-477110-q6"
        )
        dataset_id = os.getenv("BIGQUERY_DATASET") or "analytics"
        table_id = os.getenv("BIGQUERY_TABLE") or "daily_sales"
        write_mode = os.getenv("BQ_WRITE_MODE", "append")

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        client = bigquery.Client(project=project_id)
        dataset_ref = f"{project_id}.{dataset_id}"
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        # Ensure dataset exists
        try:
            client.get_dataset(dataset_ref)
        except NotFound:
            ds = bigquery.Dataset(dataset_ref)
            ds.location = os.getenv("BQ_LOCATION", "us-central1")
            client.create_dataset(ds, exists_ok=True)

        df = pd.read_parquet(self.staging_file)

        schema = None
        schema_file = os.path.join("schemas", "daily_sales_schema.json")
        if os.path.isfile(schema_file):
            schema = client.schema_from_json(schema_file)
            logger.info("Attached explicit BigQuery schema from %s", schema_file)

        try:
            client.get_table(table_ref)
        except NotFound:
            tbl = bigquery.Table(table_ref, schema=schema)
            tbl.time_partitioning = bigquery.TimePartitioning(
                type_=bigquery.TimePartitioningType.DAY,
                field="order_date",
            )
            tbl.clustering_fields = ["customer_id", "order_status"]
            client.create_table(tbl)

        job_config = bigquery.LoadJobConfig(
            write_disposition=(
                bigquery.WriteDisposition.WRITE_APPEND
                if write_mode == "append"
                else bigquery.WriteDisposition.WRITE_TRUNCATE
            ),
        )
        if schema:
            job_config.schema = schema
        if write_mode == "append":
            job_config.schema_update_options = [
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        records = self.extract()
        if records == 0:
            logger.warning("Extraction completed with 0 records.")
        valid_count = self.transform()
        if records > 0 and valid_count == 0:
            logger.error(
                "FATAL: Extracted %d records but 0 survived transformation. "
                "Schema contract violation — failing pipeline.", records
            )
            return 1
        self.load()
        logger.info("=== Pipeline Execution Finished Successfully ===")
        return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    try:
        runner = PipelineRunner(execution_date=args.date)
        exit_code = runner.run()
        if exit_code != 0:
            sys.exit(1)
        sys.exit(0)
    except Exception as exc:
        logger.critical("Pipeline failed with unhandled error: %s", exc, exc_info=True)
        sys.exit(1)
