"""Standalone Connector Pipeline: sales_etl
Generated by SDLC Data Engineer Agent.
Architecture: GCS -> Local Staging -> BIGQUERY
Mock dummy data generation is completely disabled — real extraction & loading only.
"""
import os
import sys
import json
import logging
import argparse
import uuid
import re
from datetime import datetime, timezone
import pandas as pd
from google.cloud import storage, bigquery

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [%(name)s] %(message)s",
)
logger = logging.getLogger("sales_etl")


class PipelineRunner:
    def __init__(self, execution_date: str = None):
        self.execution_date = execution_date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        self.staging_dir = os.path.join("staging", "sales_etl", self.execution_date)
        os.makedirs(self.staging_dir, exist_ok=True)
        self.staging_file = os.path.join(self.staging_dir, "data.parquet")

    def extract(self) -> int:
        """Extracts data from real GCS into staging format.
        
        Zero-mock policy: if credentials or sources are unavailable, raises an error immediately.
        """
        logger.info("Starting real extraction from source: gcs...")
        bucket_name = os.getenv("GCS_SOURCE_BUCKET") or "sdlc-workspec-store"
        prefix = os.getenv("GCS_SOURCE_PREFIX") or "etl/data/raw_sales_data.csv"
        if not bucket_name:
            raise EnvironmentError("FATAL: GCS source bucket not configured. Set GCS_SOURCE_BUCKET.")

        logger.info("Extracting real data from GCS bucket: gs://%s/%s", bucket_name, prefix)
        client = storage.Client()
        bucket = client.bucket(bucket_name)
        blobs = [b for b in bucket.list_blobs(prefix=prefix) if not b.name.endswith("/")]
        if not blobs:
            raise FileNotFoundError(f"FATAL: No data files found in gs://{bucket_name}/{prefix}. Mock fallback disabled.")

        dfs = []
        for blob in blobs:
            local_path = os.path.join(self.staging_dir, os.path.basename(blob.name))
            blob.download_to_filename(local_path)
            if local_path.endswith(".parquet"):
                dfs.append(pd.read_parquet(local_path))
            elif local_path.endswith(".csv"):
                dfs.append(pd.read_csv(local_path))
            elif local_path.endswith(".json") or local_path.endswith(".jsonl"):
                dfs.append(pd.read_json(local_path, lines=True))

        if not dfs:
            raise FileNotFoundError(f"FATAL: No parseable data files found in gs://{bucket_name}/{prefix}")

        df = pd.concat(dfs, ignore_index=True)
        row_count = len(df)
        df.to_parquet(self.staging_file, index=False)
        logger.info("Extracted %d real records from GCS to %s", row_count, self.staging_file)
        return row_count

    def transform(self) -> int:
        """Schema-adaptive transformation with cleaning, deduplication, and circuit breaker."""
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file is empty. Nothing to transform.")
            return 0

        df = pd.read_parquet(self.staging_file)
        raw_count = len(df)
        if raw_count == 0:
            logger.warning("Staging DataFrame is empty. Nothing to transform.")
            return 0

        logger.info("Transforming %d raw records. Columns: %s", raw_count, list(df.columns))

        # Standardize column names
        df.columns = [
            re.sub(r"[^a-zA-Z0-9_]+", "_", str(col).strip().lower()).strip("_")
            for col in df.columns
        ]

        # Strip strings
        for col in df.select_dtypes(include=["object", "string"]).columns:
            df[col] = df[col].astype(str).str.strip().replace({"nan": None, "None": None, "": None})

        # Required columns check
        for req in ["order_id", "amount", "created_at"]:
            if req not in df.columns:
                raise ValueError(f"Required column '{req}' is missing from source dataset.")

        # Filter valid rows
        df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
        valid_mask = df["order_id"].notna() & df["created_at"].notna() & df["amount"].notna() & (df["amount"] >= 0)
        df_valid = df[valid_mask].copy()

        quarantined = raw_count - len(df_valid)
        error_pct = (quarantined / raw_count) * 100.0 if raw_count > 0 else 0.0

        if error_pct > 15.0 or len(df_valid) == 0:
            logger.error("FATAL: Circuit breaker triggered with error rate %.2f%%", error_pct)
            sys.exit(1)

        # Parse timestamps and derive order_date
        df_valid["created_at"] = pd.to_datetime(df_valid["created_at"], utc=True, errors="coerce")
        df_valid["order_date"] = df_valid["created_at"].dt.date

        # Deduplicate on order_id
        df_valid = df_valid.sort_values(by="created_at").drop_duplicates(subset=["order_id"], keep="last")

        # Ingestion metadata
        df_valid["ingested_at"] = datetime.now(timezone.utc).isoformat()
        df_valid["batch_id"] = str(uuid.uuid4())

        df_valid.to_parquet(self.staging_file, index=False)
        logger.info("Transform complete: raw=%d, valid_after_dedup=%d, quarantined=%d", raw_count, len(df_valid), quarantined)
        return len(df_valid)

    def load(self) -> bool:
        """Loads staged records into real BigQuery destination."""
        logger.info("Loading staged file %s into BigQuery (analytics.daily_sales)...", self.staging_file)
        if not os.path.exists(self.staging_file) or os.path.getsize(self.staging_file) == 0:
            logger.warning("Staging file %s is empty or missing. Skipping load phase.", self.staging_file)
            return True

        project_id = os.getenv("GCP_PROJECT_ID") or os.getenv("PROJECT_ID", "upbeat-repeater-477110-q6")
        dataset_id = os.getenv("BIGQUERY_DATASET", "analytics")
        table_id = os.getenv("BIGQUERY_TABLE", "daily_sales")

        if not project_id:
            raise EnvironmentError("FATAL: GCP_PROJECT_ID or PROJECT_ID must be set for BigQuery loading.")

        client = bigquery.Client(project=project_id)
        table_ref = f"{project_id}.{dataset_id}.{table_id}"

        df = pd.read_parquet(self.staging_file)

        job_config = bigquery.LoadJobConfig(
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            time_partitioning=bigquery.TimePartitioning(
                type_=bigquery.TimePartitioningType.DAY,
                field="order_date"
            ),
            clustering_fields=["customer_id", "order_status"] if "order_status" in df.columns else None,
            schema_update_options=[
                bigquery.SchemaUpdateOption.ALLOW_FIELD_ADDITION,
                bigquery.SchemaUpdateOption.ALLOW_FIELD_RELAXATION,
            ]
        )

        schema_file = "schemas/daily_sales_schema.json"
        if os.path.isfile(schema_file):
            with open(schema_file, "r", encoding="utf-8") as f:
                schema_json = json.load(f)
            job_config.schema = [
                bigquery.SchemaField(
                    name=col["name"],
                    field_type=col["type"],
                    mode=col.get("mode", "NULLABLE"),
                    description=col.get("description")
                )
                for col in schema_json if col.get("name")
            ]
            logger.info("Attached explicit BigQuery schema from %s", schema_file)

        job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
        job.result()

        if job.errors:
            raise RuntimeError(f"FATAL: BigQuery load job failed: {job.errors}")

        logger.info("Successfully loaded %d records into BigQuery table: %s", len(df), table_ref)
        return True

    def run(self) -> int:
        """Executes the end-to-end connector pipeline with fail-fast semantics."""
        logger.info("=== Starting Connector Pipeline Execution ===")
        records = self.extract()
        if records == 0:
            logger.warning("Extraction completed with 0 records.")
        valid_count = self.transform()
        if records > 0 and valid_count == 0:
            logger.error(
                "FATAL: Extracted %d records but 0 survived transformation. Schema contract violation.",
                records
            )
            return 1
        self.load()
        logger.info("=== Pipeline Execution Finished Successfully ===")
        return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Connector Pipeline Runner")
    parser.add_argument("--date", help="Execution date (YYYY-MM-DD)", default=None)
    args = parser.parse_args()

    runner = PipelineRunner(execution_date=args.date)
    exit_code = runner.run()
    if exit_code != 0:
        sys.exit(1)
    sys.exit(0)
